topic=${TOPIC:sensor_topic}
consumer.group.id=${CONSUMER_GROUP:central_service_group}
bootstrap.server=${BOOTSTRAP_SERVER:kafka:9092}

temperature.threshold=[\
  {\
    "sensorId": ["t1", "t2"],\
    "threshold": 35\
  }, \
  {\
    "sensorId": ["t3", "t4"],\
    "threshold": 30\
  }\
]
humidity.threshold=[\
  {"sensorId":["h1", "h2"],"threshold": 55}\
  , {"sensorId":["h3", "h4"],"threshold": 60}\
  ]

